
-- Schéma

DROP SCHEMA IF EXISTS contacts CASCADE;
CREATE SCHEMA contacts;


-- Tables

CREATE TABLE compte (
	idcompte		INT				GENERATED BY DEFAULT AS IDENTITY,
	pseudo			VARCHAR(25)		NOT NULL,
	motdepasse		VARCHAR(25) 	NOT NULL,
	email			VARCHAR(100)	NOT NULL,
	UNIQUE (pseudo),
	PRIMARY KEY (idcompte)
);

CREATE TABLE role (
	idcompte		INT				NOT NULL,
	role			VARCHAR(20)		NOT NULL,
	CHECK( Role IN ('ADMINISTRATEUR','UTILISATEUR') ),	
	FOREIGN KEY (idcompte) REFERENCES compte (idcompte) ON DELETE CASCADE,
	PRIMARY KEY (idcompte, role)
);

CREATE TABLE categorie (
	idcategorie		INT				GENERATED BY DEFAULT AS IDENTITY,
	libelle			VARCHAR(25)		NOT NULL,
	debut			DATE,
	PRIMARY KEY (idcategorie)
);

CREATE TABLE personne (
	idpersonne		INT				GENERATED BY DEFAULT AS IDENTITY,
	idcategorie		INT				NOT NULL,
	nom				VARCHAR(25)  	NOT NULL,
	prenom			VARCHAR(25) 	NOT NULL,
	FOREIGN KEY (idcategorie) REFERENCES categorie (idcategorie),
	PRIMARY KEY (idpersonne)
);

CREATE TABLE telephone (
	idtelephone		INT				GENERATED BY DEFAULT AS IDENTITY,
	idpersonne		INT			 	NOT NULL,
	Libelle			VARCHAR(25)		NOT NULL,
	Numero			VARCHAR(25)		NOT NULL,
	FOREIGN KEY (idpersonne) REFERENCES personne (idpersonne) ON DELETE CASCADE,
	PRIMARY KEY (idtelephone)
);

CREATE TABLE memo (
	idmemo  		INT				GENERATED BY DEFAULT AS IDENTITY,
	idcategorie     INT,
	titre		    VARCHAR(50)		NOT NULL,
	description	    VARCHAR(1000),
	flagurgent       BOOLEAN 	NOT NULL,
	statut           CHAR(1)    NOT NULL CHECK (statut IN('A','E','F')),
	effectif         INT  ,
	budget          NUMERIC (12,2),
	echeance        DATE,
	heure           TIME,
	FOREIGN KEY (idcategorie) REFERENCES categorie (idcategorie),
	PRIMARY KEY (idmemo)
);
CREATE TABLE service (
	idservice  		INT				GENERATED BY DEFAULT AS IDENTITY,
	idpersonne     INT,
	nom		    VARCHAR(50)		NOT NULL,
	anneecreation	    INT,
	flagsiege       BOOLEAN 	NOT NULL,
	FOREIGN KEY (idpersonne) REFERENCES personne (idpersonne),
	PRIMARY KEY (idservice)
);
CREATE TABLE abonner (
    idmemo INT NOT NULL,
    idcompte INT NOT NULL,
	FOREIGN KEY (idmemo) REFERENCES memo (idmemo) ON DELETE CASCADE,
	FOREIGN KEY (idcompte) REFERENCES compte (idcompte) ON DELETE CASCADE,
	PRIMARY KEY (idmemo, idcompte)
);

CREATE TABLE agir (
	idmemo INT NOT NULL,
	idpersonne INT NOT NULL,
	fonction VARCHAR(100),
	debut DATE,
	FOREIGN KEY (idmemo) REFERENCES memo (idmemo) ON DELETE CASCADE,
	FOREIGN KEY (idpersonne) REFERENCES personne (idpersonne) ON DELETE CASCADE,
	PRIMARY KEY (idmemo, idpersonne)
);

